services:
  - type: web
    name: telegram-inventory-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: ваш_токен_бота
